# Generated by Django 4.2.16 on 2025-07-13 00:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Immobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('type_item', models.CharField(choices=[('APARTAMENTO', 'APARTAMENTO'), ('KITNET', 'KITNET'), ('CASA', 'CASA')], max_length=100)),
                ('address', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_locate', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data da Visita')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='myapp.client')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='myapp.employee')),
                ('immobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='myapp.immobile')),
            ],
            options={
                'verbose_name': 'Agendamento de Visita',
                'verbose_name_plural': 'Agendamentos de Visitas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RegisterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_start', models.DateTimeField(verbose_name='Inicio')),
                ('dt_end', models.DateTimeField(verbose_name='Fim')),
                ('create_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('immobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_location', to='myapp.immobile')),
            ],
            options={
                'verbose_name': 'Registrar Locação',
                'verbose_name_plural': 'Registrar Locação',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('payment_date', models.DateField(verbose_name='Data do Pagamento')),
                ('method', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro')], max_length=20, verbose_name='Forma de Pagamento')),
                ('register_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.registerlocation')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição do problema')),
                ('request_date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
                ('register_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='myapp.registerlocation')),
            ],
            options={
                'verbose_name': 'Solicitação de Manutenção',
                'verbose_name_plural': 'Solicitações de Manutenção',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='ImmobileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Images')),
                ('immobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobile_images', to='myapp.immobile')),
            ],
        ),
        migrations.AddField(
            model_name='immobile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immobiles', to='myapp.owner'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='contracts/', verbose_name='Documento do Contrato')),
                ('signed_date', models.DateField(verbose_name='Data de Assinatura')),
                ('register_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='myapp.registerlocation')),
            ],
            options={
                'verbose_name': 'Contrato de Aluguel',
                'verbose_name_plural': 'Contratos de Aluguel',
                'ordering': ['-id'],
            },
        ),
    ]
